vsm_app/urls.py
from django.contrib import admin
from django.urls import path
from vsm_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.home, name="index"),
    path("home", views.home, name="home"),
    path("registros", views.registros, name="registros"),
    path("nuevo_vsm", views.nuevo_vsm, name="nuevo_vsm"),
    path("editar_vsm/<int:id>", views.editar_vsm, name="editar_vsm"),
    path("vsm/<int:vsm_id>/eliminar/", views.eliminar_vsm, name="eliminar_vsm"),
    path("pendientes", views.listar_vsm_pendientes, name="listar_vsm_pendientes"),
    path("entregar/<int:vsm_id>", views.confirmar_entrega, name="confirmar_entrega"),
    path(
        "rechazar_entrega/<int:vsm_id>",
        views.rechazar_entrega,
        name="rechazar_entrega",
    ),
    path("detalle_vsm/<int:vsm_id>", views.detalle_vsm, name="detalle_vsm"),
    path("buscar_solicitantes", views.buscar_solicitantes, name="buscar_solicitantes"),
    path(
        "ajax/empleados",
        views.obtener_empleados_por_centro,
        name="obtener_empleados_por_centro",
    ),
    path(
        "api/materiales",
        views.get_materiales_por_centro,
        name="get_materiales_por_centro",
    ),
    path(
        "buscar_productos_por_centro",
        views.buscar_productos_por_centro,
        name="buscar_productos_por_centro",
    ),
    path(
        "pendiente/<int:vsm_id>/editar",
        views.editar_pendiente,
        name="editar_pendiente",
    ),
    path(
        "pendiente/<int:vsm_id>/rechazar",
        views.rechazar_pendiente,
        name="rechazar_pendiente",
    ),
    path("pendiente/<int:vsm_id>/ver", views.ver_pendiente, name="ver_pendiente"),
    path("generar_pdf/<int:vsm_id>", views.generar_pdf, name="generar_pdf"),
    path(
        "generar_template_insumo/<int:vsm_id>",
        views.generar_template_insumo,
        name="generar_template_insumo",
    ),
    path(
        "generar_template_epp/<int:vsm_id>",
        views.generar_template_epp,
        name="generar_template_epp",
    ),
    path("get_tags/<int:empleado_id>", views.get_tags_por_empleado, name="get_tags"),
    path("test_sap_connection", views.test_sap_connection, name="test_sap_connection"),
    path("ajax/consultar_stock", views.consultar_stock, name="consultar_stock"),
    path('ajax/almacenes_por_empresa/', views.obtener_almacenes_por_empresa, name='obtener_almacenes_por_empresa'),
    path('vsm/aprobar/<int:vsm_id>/', views.aprobar_vsm, name='aprobar_vsm'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vsm_frigo/urls.py
from django.contrib import admin
from django.urls import path, include, re_path # Importar re_path
from django.views.generic import RedirectView
from mozilla_django_oidc.views import OIDCLogoutView
from vsm_app.logout import LogoutView

urlpatterns = [
    # Solución para /admin sin barra final (mantener la corrección anterior)
    re_path(r'^admin$', RedirectView.as_view(url='/admin/', permanent=True)), 

    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path(
        "auth/login/",
        RedirectView.as_view(url="/oidc/authenticate/", permanent=True),
        name="keycloak_login",
    ),
    path("auth/logout/", LogoutView.as_view(), name="keycloak_logout"),

    re_path(r'^oidc/', include("mozilla_django_oidc.urls")),
    
    path('', include('vsm_app.urls')),
]

vsm_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class centro_costos(models.Model):
    codigo = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.codigo} - {self.descripcion}"

class almacenes(models.Model):
    almacen = models.CharField(max_length=5)
    empresa = models.ForeignKey(
        "empresas", on_delete=models.CASCADE, null=True, blank=True
    )

    def __str__(self):
        return f"{self.almacen} - {self.empresa.empresa if self.empresa else 'Sin Empresa'}"
    
class empresas (models.Model):
    empresa = models.CharField(max_length=5)
    descripcion = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.empresa} - {self.descripcion}"

class empleados(models.Model):
    legajo = models.IntegerField(unique=True)
    nombre = models.CharField(max_length=100)
    cc = models.ForeignKey(
        centro_costos, on_delete=models.CASCADE, null=True, blank=True
    )
    nro_tarjeta = models.ManyToManyField("nro_tarjeta", blank=True)
    perfil_riesgo = models.ForeignKey(
        "perfil_riesgo", on_delete=models.SET_NULL, null=True, blank=True
    )

    def __str__(self):
        return f"{self.nombre} - {self.cc.descripcion if self.cc else 'Sin CC'}"


class maestro_de_materiales(models.Model):
    codigo = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=200)
    clase_sap = models.CharField(max_length=10)
    centro = models.CharField(max_length=4)
    almacen = models.OneToOneField(
        almacenes, on_delete=models.CASCADE, null=True, blank=True
    )

    def __str__(self):
        return f"{self.codigo} - {self.descripcion}"


class permisos(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    descripcion = models.CharField(max_length=30, blank=True, null=True)

    def __str__(self):
        return self.nombre


class Usuarios(AbstractUser):
    empleado = models.OneToOneField(
        empleados, on_delete=models.CASCADE, null=True, blank=True
    )
    permisos = models.ManyToManyField(permisos, related_name="usuarios", blank=True)
    cc_permitidos = models.ManyToManyField(
        centro_costos, related_name="usuarios_permitidos", blank=True
    )
    empresas = models.ManyToManyField(
        empresas, related_name="usuarios_empresas", blank=True
    )

    def __str__(self):
        return self.username

    def get_user_permissions(self):
        return self.permisos.all()


class VSM(models.Model):
    ESTADO_CHOICES = [
        ("pendiente", "Pendiente"),
        ("entregado", "Entregado"),
        ("rechazado", "Rechazado"),
    ]
    centro_costos = models.ForeignKey(centro_costos, on_delete=models.CASCADE)
    solicitante = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    retirante = models.ForeignKey(
        empleados, related_name="retirante", on_delete=models.CASCADE
    )
    productos = models.ManyToManyField("maestro_de_materiales", through="VSMProducto")
    tipo_entrega = models.CharField(
        max_length=20,
        choices=[("INSUMOS", "Insumos"), ("EPP", "EPP")],
        null=True,
        blank=True,
    )
    tipo_facturacion = models.CharField(
        max_length=20,
        choices=[("FACTURADO", "Facturado"), ("NO_FACTURADO", "No facturado")],
        null=True,
        blank=True,
    )
    fecha_solicitud = models.DateTimeField(auto_now_add=True)
    fecha_entrega = models.DateTimeField(null=True, blank=True)
    estado = models.CharField(
        max_length=20, choices=ESTADO_CHOICES, default="pendiente"
    )
    observaciones = models.TextField(null=True, blank=True)
    observaciones_entrega = models.TextField(null=True, blank=True)
    numero_sap = models.CharField(max_length=50, blank=True, null=True)
    anio_documento = models.CharField(max_length=4, null=True, blank=True)
    almacen = models.ForeignKey(almacenes, on_delete=models.CASCADE, null=True, blank=True)
    active = models.BooleanField(default=True)
    estado_sap = models.CharField(
        max_length=20,
        choices=[
            ("procesado", "Procesado"),
            ("no_procesado", "No Procesado"),
            ("error", "Error"),
        ],
        default="no_procesado",
    )
    actualizado = models.DateTimeField(auto_now=True)
    estado_aprobacion = models.CharField(
        max_length=20,
        choices=[
            ("APROBADO", "Aprobado"), 
            ("RECHAZADO", "Rechazado"), 
            ("PENDIENTE", "Pendiente")
        ],
        default="APROBADO",
    )

    def entrega_completa(self):
        return (
            self.estado == "entregado"
            and self.cantidad_entregada == self.cantidad_solicitada
        )

class VSMProducto(models.Model):
    vsm = models.ForeignKey(VSM, on_delete=models.CASCADE)
    producto = models.ForeignKey("maestro_de_materiales", on_delete=models.CASCADE)
    cantidad_solicitada = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad_entregada = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, blank=True, default=0
    )
    firma_retirante = models.ImageField(upload_to="firmas/", null=True, blank=True)

    def __str__(self):
        return f"{self.producto.descripcion} - {self.cantidad_solicitada} unidades"


class PermisoRetiro(models.Model):
    centro_costo = models.ForeignKey(centro_costos, on_delete=models.CASCADE)
    producto = models.ManyToManyField(maestro_de_materiales)

    def __str__(self):
        return f"{self.centro_costo} - {self.centro_costo.descripcion}"


class tags_productos(models.Model):
    descripcion = models.CharField(max_length=20)

    def __str__(self):
        return self.descripcion


class perfil_riesgo(models.Model):
    nombre = models.CharField(max_length=100)
    tags_productos = models.ManyToManyField(
        tags_productos, related_name="perfiles", blank=True, default=None
    )

    def __str__(self):
        return self.nombre


class nro_tarjeta(models.Model):
    numero = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.numero}"


class relacion_cc_perfil_riesgo(models.Model):
    centro_costo = models.ForeignKey(centro_costos, on_delete=models.CASCADE)
    perfil_riesgo = models.ForeignKey(perfil_riesgo, on_delete=models.CASCADE)
    default = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.centro_costo} - {self.perfil_riesgo}"

    class Meta:
        unique_together = ("centro_costo", "perfil_riesgo", "default")

class permiso_empresa_almacen(models.Model):
    empresa = models.ForeignKey(empresas, on_delete=models.CASCADE)
    almacen = models.ForeignKey(almacenes, on_delete=models.CASCADE)
    requiere_aprobacion = models.BooleanField(default=False)
    usuarios_aprobadores = models.ManyToManyField(Usuarios, blank=True)

    def __str__(self):
        return f"{self.empresa} - {self.almacen}"

    class Meta:
        unique_together = ("empresa", "almacen")

vsm_app/templates/aprobar_vsm.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Aprobar Entrega VSM #{{ vsm.id }}{% endblock %}

{% block content %}
{% include 'navbar.html' %}


<div class="flex justify-center mt-4">
    <div class="w-full max-w-5xl"> 
        {% if messages %}
            {% for message in messages %}
                <div class="alert 
                    {% if message.tags == 'error' %}alert-error{% elif message.tags == 'success' %}alert-success{% else %}alert-info{% endif %} 
                    shadow-lg mb-4">
                    <div>
                        <span class="text-lg">
                            {{ message }}
                        </span>
                    </div>
                    <button type="button" class="btn btn-sm btn-circle absolute top-2 right-2" onclick="this.parentElement.style.display='none';">
                        ✕
                    </button>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</div>
<body class="justify-center">

  <div class="bg-base-200 w-full mt-2 mx-auto  max-w-3xl sm:max-w-4xl md:max-w-5xl p-3 sm:p-5 md:p-8 rounded-2xl shadow-xl">
    
    <h1 class="text-2xl font-semibold text-center mt-0 mb-6">Revisar y Aprobar VSM #{{ vsm.id }}</h1>

        <form action="{% url 'aprobar_vsm' vsm.id %}" method="post" class="space-y-4" id="formAprobar">
      {% csrf_token %}
      
      <div>
        <p class="bg-base-100 p-3 rounded-2xl"><span class="font-extrabold">Tipo VSM:</span> {{ vsm.get_tipo_entrega_display }}</p>
        <p class="bg-base-100 p-3 rounded-2xl"><span class="font-extrabold">Estado Aprobación:</span> <span class="badge badge-warning">{{ vsm.get_estado_aprobacion_display }}</span></p>
        <p class="bg-base-100 p-3 rounded-2xl"><span class="font-extrabold">Solicitante:</span> {{ vsm.solicitante }}</p>
        <p class="bg-base-100 p-3 rounded-2xl"><span class="font-extrabold">Retirante:</span> {{ vsm.retirante }}</p>
      </div>

            <h3 class="text-xl font-semibold mt-3 mb-3">Ítems Solicitados</h3>
      <table class="w-full text-sm border border-gray-600 rounded-lg overflow-hidden bg-base-100">
        <thead>
          <tr>
            <th class="text-left px-4 py-2">Producto</th>
            <th class="text-center px-4 py-2">Cantidad Solicitada</th>
          </tr>
        </thead>
        <tbody>
          {% for vsm_producto in vsm.vsmproducto_set.all %}
          <tr class="border-b border-gray-700">
            <td class="px-4 py-3">{{ vsm_producto.producto }}</td>
            <td class="px-4 py-3 text-center">{{ vsm_producto.cantidad_solicitada }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      
      <div class="flex justify-center items-center gap-4 pt-6">
        <button type="submit" id="btnAprobarVSM"
                class="btn btn-lg btn-success py-3 rounded-xl font-medium text-lg">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" /></svg>
          Aprobar VSM
        </button>
        
        <a href="{% url 'listar_vsm_pendientes' %}" class="btn btn-secondary px-6 py-2 rounded-xl font-medium text-sm">
          Cancelar y Volver
        </a>
      </div>
      
    </form>
  </div>

<div id="loaderOverlay" class="fixed inset-0 bg-base-300 bg-opacity-50 flex items-center justify-center hidden z-50">
  <div class="bg-white text-black px-6 py-4 rounded-lg flex flex-col items-center shadow-lg">
    <span class="loader mb-3"></span>
    <p class="text-lg font-semibold">Procesando aprobación, por favor espere...</p>
  </div>
</div>
{% endblock %}

vsm_app/templates/editar_pendiente.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Editar VSM Pendiente{% endblock %}
{% block content %}
{% include 'navbar.html' %}

<body>

  <div class="w-full max-w-xl sm:max-w-2xl md:max-w-3xl rounded-2xl shadow-lg p-8 bg-base-300 mx-auto my-10">
    <h1 class="text-2xl font-bold text-center mb-6" style="color: var(--detalle-dorado);">
      ✏️ Editar VSM Pendiente
    </h1>

    <span class="text-sm text-gray-500">VSM ID : {{ vsm.id }}</span>

    <form method="POST" class="space-y-6">
      {% csrf_token %}

      <!-- Solicitante -->
      <div>
        <label for="solicitante" class="block mb-2 font-semibold">Solicitante</label>
        <input type="text" id="solicitante" name="solicitante" 
               value="{{ vsm.solicitante }}" 
               class="w-full px-2 py-1 rounded bg-neutral" required readonly>
      </div>
      <!-- Tipo de Entrega -->
      <div>
        <label for="tipo_entrega" class="block mb-2 font-semibold">Tipo de entrega</label>
        <input type="text" readonly id="tipo_entrega" name="tipo_entrega" 
               value="{{ vsm.get_tipo_entrega_display }}" 
               class="w-full p-2 rounded bg-neutral">
      </div>
      <!-- Tipo de Facturación -->
      <div>
        <label for="tipo_facturacion" class="block mb-2 font-semibold">Tipo de facturación</label>
        <select id="tipo_facturacion" name="tipo_facturacion" 
                class="w-full p-2 rounded bg-base-100">
          <option value="FACTURADO" {% if vsm.tipo_facturacion == "FACTURADO" %}selected{% endif %}>Facturado</option>
          <option value="NO_FACTURADO" {% if vsm.tipo_facturacion == "NO_FACTURADO" %}selected{% endif %}>No facturado</option>
        </select>
      </div>

      <!-- Centro de Costos -->
      <div>
        <label for="centro_costos" class="block mb-2 font-semibold">Centro de Costos</label>
        <input type="text" id="centro_costos" name="centro_costos" 
               value="{{ vsm.centro_costos.descripcion }}" 
               class="w-full p-2 rounded bg-neutral" required readonly>
      </div>

      <!-- Retirante -->
      <div>
        <label for="retirante" class="block mb-2 font-semibold">Retirante</label>
        <select id="retirante" name="retirante" 
                class="select2 w-full p-2 rounded bg-base-100">
          <option value="">Seleccione un retirante</option>
          {% for empleado in empleados %}
            <option value="{{ empleado.id }}" {% if vsm.retirante.id == empleado.id %}selected{% endif %}>
              {{ empleado.nombre }}
            </option>
          {% endfor %}
        </select>
      </div>

      <!-- Observaciones -->
      <div>
        <label for="detalles" class="block mb-2 font-semibold">Observaciones</label>
        <textarea id="detalles" name="detalles" rows="4"
                  class="w-full p-1 rounded bg-base-100">{{ vsm.observaciones }}</textarea>
      </div>
      
      <!-- Productos -->
      <div>
        <label class="block mb-2 font-semibold">Productos</label>
        <div class="space-y-4">
          {% for producto in vsm.vsmproducto_set.all %}
            <div class="flex items-center">
              <span class="flex-1">{{ producto.producto.descripcion }}</span>
              <input type="number" 
                    name="cantidad_{{ producto.id }}" 
                    min="0" 
                    value="{{ producto.cantidad_solicitada }}" 
                    class="w-24 p-2 rounded bg-base-100 border">
            </div>
          {% endfor %}
        </div>
      </div>

      <!-- Botones -->
      <div class="flex justify-between mt-6">
        <a href="{% url 'registros' %}" 
           class="px-6 py-2 rounded-lg btn text-white font-semibold">
          ⬅ Volver
        </a>
        <button type="submit" 
                class="px-6 py-2 rounded-lg btn font-bold">
          💾 Guardar cambios
        </button>
      </div>
    </form>
  </div>

</body>

{% endblock %}

vsm_app/templates/epp_pdf.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Constancia de Entrega</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <style>
    body {
      font-family: Arial, sans-serif;
      font-size: 13px;
    }
    table {
      border-collapse: collapse;
      width: 100%;
    }
    th, td {
      border: 1px solid #000;
      padding: 6px;
      text-align: center;
      vertical-align: middle;
      border-collapse: collapse;
    }
    th {
      background-color: #f2f2f2;
    }
    .no-border td {
      border: none;
      text-align: left;
    }
    .header {
      font-weight: bold;
      text-align: center;
      padding: 10px;
      font-size: 14px;
    }
    .firma {
      height: 60px;
    }


  </style>
</head>

<div style="display: flex; justify-content: space-around; align-items: center; margin-top: 1rem; width: 15%;">
    <div>
        <a href="{% url 'registros' %}" class="m-10"><button class="btn btn-primary m-6">< Volver</button></a>
    </div>
    <div>
        <a href="" class="m-10"><button class="btn btn-success m-6" onclick="printSection('pdf-content')"><i class="bi bi-printer"></i> Imprimir</button></a>
    </div>
</div>

    <div class="container" style="padding: 0%; margin: 2rem auto 2rem auto;" id="pdf-content">
        <table>
            <tr>
                <td>
                    <img src="{% static 'images/logo.svg' %}" alt="Logo Frigo" width="160">
                </td>
            <td>
                CONSTANCIA DE ENTREGA DE ROPA DE TRABAJO Y ELEMENTOS DE PROTECCIÓN PERSONAL
            </td>
            </tr>
        </table>

        <table>
            <tr>
            <td><b>RAZÓN SOCIAL:</b> {{ vsm.retirante.razon_social }} </td>
            <td><b>CUIT:</b> {{ vsm.retirante.cuil }} </td>
            <td><b>DIRECCIÓN:</b> Av. De los CONSTITUYENTES 2499</td>
            <td><b>LOCALIDAD:</b> PACHECO</td>
            </tr>
            <tr>
            <td><b>CP:</b> 1617</td>
            <td colspan="2"><b>NOMBRE Y APELLIDO DEL TRABAJADOR:</b> {{ vsm.retirante.nombre }} {{ vsm.retirante.apellido }}</td>
            <td><b>DNI:</b> {{ vsm.retirante.dni }}</td>
            </tr>
            <tr>
            <td><b>LEGAJO:</b> {{ vsm.retirante.legajo }}</td>
            <td colspan="3"><b>PERFIL DE RIESGO (DESCRIPCIÓN):</b> {{ vsm.retirante.perfil_riesgo }}</td>
            </tr>
        </table>

        <p style="font-size: 12px; margin: 0px 0; border-top: none; border-bottom: none; border-left: #000 1px solid; border-right: #000 1px solid; padding: 5px; text-align: justify;">
            ELEMENTOS DE PROTECCIÓN NECESARIOS PARA EL TRABAJADOR, SEGÚN EL PUESTO:<br>
            SUPERINTENDENCIA DE RIESGOS DE TRABAJO. RESOLUCIÓN 299/2011. ADÓPTENSE LAS REGLAMENTACIONES QUE PROCUREN LA PROVISIÓN DE ELEMENTOS DE PROTECCIÓN PERSONAL
        </p>

        <table>
            <thead>
            <tr>
                <th>PRODUCTO</th>
                <th>TIPO/MODELO</th>
                <th>MARCA</th>
                <th>POSEE CERTIFICACIÓN SI/NO</th>
                <th>CANTIDAD</th>
                <th>FECHA DE ENTREGA</th>
                <th>FIRMA DEL TRABAJADOR</th>
                <th>OBSERVACIONES</th>
            </tr>
            </thead>
            <tbody>
            {% for producto in vsm.vsmproducto_set.all %}
            <tr>
                <td>{{ producto.producto.descripcion }}</td>
                <td>{{ producto.producto.descripcion }}</td>
                <td>{{ producto.marca }}</td>
                <td>SI</td>
                <td>{{ producto.cantidad_entregada }}</td>
                <td>{{ vsm.fecha_entrega|date:"d-m-Y" }}</td>
                {% if vsm.estado == 'entregado' %}
                <td style="font-weight: bolder;"><img src="{{ producto.firma_retirante.url }}" alt="Firma"
                 width="80" height="80"></td>
                {% else %}
                <td style="font-weight: bolder;"></td>
                {% endif %}
                <td></td>
            </tr>
            {% endfor %}
            <tr><td colspan="8">&nbsp;</td></tr>
            </tbody>
        </table>
        <!-- Disposiciones -->
        <p style="font-size: 12px; margin: 0px 0; border-top: none; border-bottom: none; border-left: #000 1px solid; border-right: #000 1px solid; padding: 5px; text-align: justify;">
            De la Ley 19587 de Higiene y Seguridad en el Trabajo Art. 10: El trabajador estará obligado a:<br>
            Cumplir con las normas de Higiene y Seguridad y con las recomendaciones que se le formulen referentes a las obligaciones de uso, conservación y cuidado del equipo de protección personal y de las propias maquinarias y procesos de trabajo. Dec. 351/79 Cap. 19 Art. 188 al 203<br>
            <b>Disposiciones de la empresa:</b><br>
            El elemento de protección personal que se le entregara será de “uso obligatorio”, siendo responsabilidad del trabajador mantenerlo en buen estado. Todo defecto rotura o deterioro del mismo deberá ser comunicado de inmediato, para proceder a su reemplazo.<br>
            Corresponderá apercibimiento en caso de encontrarse al operario trabajando sin sus elementos de protección personal.
        </p>

        <table>
            <tr>
            <td class="firma" style="width: 80%; text-align: right;">
                <!-- Firma trabajador -->
            </td>
            <td style="width: 20%; text-align: center;">
                <b>FUI NOTIFICADO</b><hr>
                {% if vsm.estado == 'entregado' %}
                    {% with vsm.vsmproducto_set.all|first as primer_producto %}
                        {% if primer_producto and primer_producto.firma_retirante %}
                            <span>
                                <img src="{{ primer_producto.firma_retirante.url }}" 
                                    alt="Firma" 
                                    width="80" 
                                    height="80">
                            </span>
                        {% endif %}
                    {% endwith %}
                {% else %}
                    {% endif %}
                <!-- Firma notificación -->
            </td>
            </tr>
        </table>
    </div>
<script>
function printSection(sectionId) {
  const section = document.getElementById(sectionId).innerHTML;
  const printWindow = window.open('', '', 'width=800,height=600');
  printWindow.document.write(`
    <html>
      <head>
        <title>Imprimir</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            font-size: 13px;
          }
          table {
            border-collapse: collapse;
            width: 100%;
          }
          th, td {
            border: 1px solid #000;
            padding: 6px;
            text-align: center;
            vertical-align: middle;
            border-collapse: collapse;
          }
          th {
            background-color: #f2f2f2;
          }
          .no-border td {
            border: none;
            text-align: left;
          }
          .header {
            font-weight: bold;
            text-align: center;
            padding: 10px;
            font-size: 14px;
          }
          .firma {
            height: 60px;
          }


        </style>
      </head>
      <body>
        ${section}
      </body>
    </html>
  `);
  printWindow.document.close();
  printWindow.focus();
  printWindow.print();
  printWindow.close();
}
</script>

</html>

vsm_app/templates/paginator.html
{% load static %}
<div class="flex justify-center mt-6 align-center">
  <nav class="inline-flex shadow-sm">
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}" class="p-6 btn bg-base-200">Anterior</a>
    {% else %}
      <span class="p-6 cursor-not-allowed btn disabled bg-base-300">Anterior</span>
    {% endif %}

    <span class="p-6 font-semibold badge badege-soft bg-base-300 mx-3">
      Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
    </span>

    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}" class="p-6 btn bg-base-200">Siguiente</a>
    {% else %}
      <span class="p-6 cursor-not-allowed btn disabled bg-base-300">Siguiente</span>
    {% endif %}
  </nav>
</div>